apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-metallb-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/diegofnunesbr/metallb-system.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
