{{- range $path, $_ := .Files.Glob "applications/*.yaml" }}
{{- $app := $.Files.Get $path | fromYaml }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name }}
  namespace: argocd
spec:
  project: {{ $.Values.projectName }}
  source:
    repoURL: {{ $app.repoURL }}
    targetRevision: {{ $app.targetRevision | default "HEAD" }}
    chart: {{ $app.chart }}
    {{- if $app.values }}
    helm:
      valuesObject:
{{ toYaml $app.values | indent 8 }}
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $app.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
